name: "Clone Manager"
slug: "clone-manager"
description: "A desktop app for batch management of local repo clones."
status: "Active"
startDate: "2026-03"
thumbnailUrl: ""
tags:
  - "dotnet"
  - "wpf/mvvm"
  - "dev tool"
